// ============================================================
//  Hazara University — Central Data Store
// ============================================================

const HU_DATA = {

  // ──────────────────────────────────────────────────────────
  //  OFFICIALS
  // ──────────────────────────────────────────────────────────
  officials: [
    // ── TOP MANAGEMENT ──────────────────────────────────────
    {
      id: 'vc',
      name: 'Prof. Dr. [Name]',
      title: 'Vice Chancellor',
      office: 'Vice Chancellor\'s Office',
      faculty: 'University Administration',
      department: 'Administration',
      email: 'vc@hu.edu.pk',
      phone: '+92-997-414137',
      officeHours: 'Monday – Wednesday, 10:00 AM – 12:00 PM',
      availability: 'limited',
      category: 'administration',
      avatar: 'VC',
      room: 'VC Block, Main Campus',
      bio: 'The Vice Chancellor is the principal academic and administrative officer of Hazara University.',
      appointmentDuration: 30,
      slots: ['10:00', '10:30', '11:00', '11:30']
    },
    {
      id: 'registrar',
      name: 'Mr. [Name]',
      title: 'Registrar',
      office: 'Registrar\'s Office',
      faculty: 'University Administration',
      department: 'Administration',
      email: 'registrar@hu.edu.pk',
      phone: '+92-997-414138',
      officeHours: 'Monday – Friday, 9:00 AM – 2:00 PM',
      availability: 'available',
      category: 'administration',
      avatar: 'RG',
      room: 'Admin Block, Ground Floor',
      bio: 'The Registrar oversees academic records, admissions, and student services.',
      appointmentDuration: 20,
      slots: ['09:00', '09:30', '10:00', '10:30', '11:00', '12:00', '13:00']
    },
    {
      id: 'coe',
      name: 'Prof. Dr. [Name]',
      title: 'Controller of Examinations',
      office: 'Examination Controller\'s Office',
      faculty: 'University Administration',
      department: 'Examinations',
      email: 'coe@hu.edu.pk',
      phone: '+92-997-414139',
      officeHours: 'Monday – Thursday, 9:00 AM – 1:00 PM',
      availability: 'available',
      category: 'administration',
      avatar: 'CE',
      room: 'Exam Block, First Floor',
      bio: 'Oversees all examination processes, scheduling, and result proclamation.',
      appointmentDuration: 20,
      slots: ['09:00', '09:30', '10:00', '11:00', '12:00']
    },
    {
      id: 'treasurer',
      name: 'Mr. [Name]',
      title: 'Treasurer',
      office: 'Treasurer\'s Office',
      faculty: 'University Administration',
      department: 'Finance',
      email: 'treasurer@hu.edu.pk',
      phone: '+92-997-414140',
      officeHours: 'Monday – Friday, 10:00 AM – 1:00 PM',
      availability: 'available',
      category: 'administration',
      avatar: 'TR',
      room: 'Admin Block, Second Floor',
      bio: 'Manages university financial resources, budgets, and fiscal planning.',
      appointmentDuration: 20,
      slots: ['10:00', '10:30', '11:00', '11:30', '12:00']
    },
    // ── DIRECTORS ────────────────────────────────────────────
    {
      id: 'dir-academics',
      name: 'Prof. Dr. [Name]',
      title: 'Director Academics',
      office: 'Academics Office',
      faculty: 'University Administration',
      department: 'Academics',
      email: 'academics@hu.edu.pk',
      phone: '+92-997-414141',
      officeHours: 'Monday – Friday, 9:00 AM – 1:00 PM',
      availability: 'available',
      category: 'directors',
      avatar: 'DA',
      room: 'Academic Block, Ground Floor',
      bio: 'Responsible for academic planning, quality, and curriculum development.',
      appointmentDuration: 20,
      slots: ['09:00', '10:00', '11:00', '12:00']
    },
    {
      id: 'dir-oric',
      name: 'Dr. [Name]',
      title: 'Director ORIC',
      office: 'Office of Research, Innovation & Commercialization',
      faculty: 'University Administration',
      department: 'Research',
      email: 'oric@hu.edu.pk',
      phone: '+92-997-414142',
      officeHours: 'Tuesday – Thursday, 10:00 AM – 12:00 PM',
      availability: 'available',
      category: 'directors',
      avatar: 'OR',
      room: 'Research Block',
      bio: 'Leads research, innovation, and industry-academia collaboration initiatives.',
      appointmentDuration: 25,
      slots: ['10:00', '10:30', '11:00', '11:30']
    },
    {
      id: 'dir-qec',
      name: 'Dr. [Name]',
      title: 'Director QEC',
      office: 'Quality Enhancement Cell',
      faculty: 'University Administration',
      department: 'Quality Assurance',
      email: 'qec@hu.edu.pk',
      phone: '+92-997-414143',
      officeHours: 'Monday – Wednesday, 9:00 AM – 11:00 AM',
      availability: 'available',
      category: 'directors',
      avatar: 'QE',
      room: 'QEC Office, Admin Block',
      bio: 'Ensures academic quality standards and continuous institutional improvement.',
      appointmentDuration: 20,
      slots: ['09:00', '09:30', '10:00', '10:30']
    },
    {
      id: 'dir-it',
      name: 'Mr. [Name]',
      title: 'Director IT',
      office: 'IT Department',
      faculty: 'University Administration',
      department: 'Information Technology',
      email: 'it@hu.edu.pk',
      phone: '+92-997-414144',
      officeHours: 'Monday – Friday, 9:00 AM – 4:00 PM',
      availability: 'available',
      category: 'directors',
      avatar: 'IT',
      room: 'IT Block',
      bio: 'Manages university IT infrastructure, digital services, and cybersecurity.',
      appointmentDuration: 15,
      slots: ['09:00', '10:00', '11:00', '13:00', '14:00', '15:00']
    },
    {
      id: 'dir-admissions',
      name: 'Mr. [Name]',
      title: 'Director Admissions',
      office: 'Admissions Office',
      faculty: 'University Administration',
      department: 'Admissions',
      email: 'admissions@hu.edu.pk',
      phone: '+92-997-414145',
      officeHours: 'Monday – Saturday, 9:00 AM – 2:00 PM',
      availability: 'available',
      category: 'directors',
      avatar: 'AD',
      room: 'Admissions Block, Ground Floor',
      bio: 'Oversees student admissions, merit lists, and enrollment processes.',
      appointmentDuration: 15,
      slots: ['09:00', '09:30', '10:00', '11:00', '12:00', '13:00']
    },
    {
      id: 'dir-finance',
      name: 'Mr. [Name]',
      title: 'Director Finance',
      office: 'Finance Office',
      faculty: 'University Administration',
      department: 'Finance',
      email: 'finance@hu.edu.pk',
      phone: '+92-997-414146',
      officeHours: 'Monday – Friday, 9:00 AM – 1:00 PM',
      availability: 'available',
      category: 'directors',
      avatar: 'DF',
      room: 'Admin Block, First Floor',
      bio: 'Manages university financial operations, fee structures, and accounts.',
      appointmentDuration: 20,
      slots: ['09:00', '10:00', '11:00', '12:00']
    },
    // ── DEANS ────────────────────────────────────────────────
    {
      id: 'dean-ncs',
      name: 'Prof. Dr. [Name]',
      title: 'Dean',
      office: 'Dean\'s Office – Faculty of Natural & Computational Sciences',
      faculty: 'Faculty of Natural & Computational Sciences',
      department: 'NCS Dean Office',
      email: 'dean.ncs@hu.edu.pk',
      phone: '+92-997-414150',
      officeHours: 'Monday – Thursday, 10:00 AM – 12:00 PM',
      availability: 'available',
      category: 'deans',
      avatar: 'DN',
      room: 'NCS Building, Dean\'s Suite',
      bio: 'Academic head of the Faculty of Natural & Computational Sciences.',
      appointmentDuration: 20,
      slots: ['10:00', '10:30', '11:00', '11:30']
    },
    {
      id: 'dean-bhs',
      name: 'Prof. Dr. [Name]',
      title: 'Dean',
      office: 'Dean\'s Office – Faculty of Biological & Health Sciences',
      faculty: 'Faculty of Biological & Health Sciences',
      department: 'BHS Dean Office',
      email: 'dean.bhs@hu.edu.pk',
      phone: '+92-997-414151',
      officeHours: 'Monday – Thursday, 10:00 AM – 12:00 PM',
      availability: 'available',
      category: 'deans',
      avatar: 'DB',
      room: 'BHS Building, Dean\'s Suite',
      bio: 'Academic head of the Faculty of Biological & Health Sciences.',
      appointmentDuration: 20,
      slots: ['10:00', '10:30', '11:00', '11:30']
    },
    {
      id: 'dean-lss',
      name: 'Prof. Dr. [Name]',
      title: 'Dean',
      office: 'Dean\'s Office – Faculty of Law & Social Sciences',
      faculty: 'Faculty of Law & Social Sciences',
      department: 'LSS Dean Office',
      email: 'dean.lss@hu.edu.pk',
      phone: '+92-997-414152',
      officeHours: 'Monday – Thursday, 10:00 AM – 12:00 PM',
      availability: 'available',
      category: 'deans',
      avatar: 'DL',
      room: 'LSS Building, Dean\'s Suite',
      bio: 'Academic head of the Faculty of Law & Social Sciences.',
      appointmentDuration: 20,
      slots: ['10:00', '10:30', '11:00', '11:30']
    },
    {
      id: 'dean-ah',
      name: 'Prof. Dr. [Name]',
      title: 'Dean',
      office: 'Dean\'s Office – Faculty of Arts & Humanities',
      faculty: 'Faculty of Arts & Humanities',
      department: 'AH Dean Office',
      email: 'dean.ah@hu.edu.pk',
      phone: '+92-997-414153',
      officeHours: 'Monday – Thursday, 10:00 AM – 12:00 PM',
      availability: 'available',
      category: 'deans',
      avatar: 'DP',
      room: 'Arts Building, Dean\'s Suite',
      bio: 'Academic head of the Faculty of Arts & Humanities.',
      appointmentDuration: 20,
      slots: ['10:00', '10:30', '11:00', '11:30']
    },
    // ── CHAIRMEN / HODs ──────────────────────────────────────
    {
      id: 'hod-cs',
      name: 'Dr. [Name]',
      title: 'Head of Department',
      office: 'Department of Computer Science',
      faculty: 'Faculty of Natural & Computational Sciences',
      department: 'Computer Science',
      email: 'hod.cs@hu.edu.pk',
      phone: '+92-997-414160',
      officeHours: 'Monday – Friday, 9:00 AM – 11:00 AM',
      availability: 'available',
      category: 'hods',
      avatar: 'CS',
      room: 'CS Building, Room 101',
      bio: 'Academic head of the Computer Science department.',
      appointmentDuration: 15,
      slots: ['09:00', '09:30', '10:00', '10:30']
    },
    {
      id: 'hod-ai',
      name: 'Dr. [Name]',
      title: 'Head of Department',
      office: 'Department of Artificial Intelligence',
      faculty: 'Faculty of Natural & Computational Sciences',
      department: 'Artificial Intelligence',
      email: 'hod.ai@hu.edu.pk',
      phone: '+92-997-414161',
      officeHours: 'Monday – Friday, 9:00 AM – 11:00 AM',
      availability: 'available',
      category: 'hods',
      avatar: 'AI',
      room: 'CS Building, Room 105',
      bio: 'Academic head of the AI department.',
      appointmentDuration: 15,
      slots: ['09:00', '09:30', '10:00', '10:30']
    },
    {
      id: 'hod-math',
      name: 'Dr. [Name]',
      title: 'Head of Department',
      office: 'Department of Mathematics',
      faculty: 'Faculty of Natural & Computational Sciences',
      department: 'Mathematics',
      email: 'hod.math@hu.edu.pk',
      phone: '+92-997-414162',
      officeHours: 'Monday – Friday, 9:00 AM – 11:00 AM',
      availability: 'available',
      category: 'hods',
      avatar: 'MT',
      room: 'NCS Building, Room 201',
      bio: 'Academic head of the Mathematics department.',
      appointmentDuration: 15,
      slots: ['09:00', '10:00', '11:00']
    },
    {
      id: 'hod-physics',
      name: 'Dr. [Name]',
      title: 'Head of Department',
      office: 'Department of Physics',
      faculty: 'Faculty of Natural & Computational Sciences',
      department: 'Physics',
      email: 'hod.physics@hu.edu.pk',
      phone: '+92-997-414163',
      officeHours: 'Monday – Friday, 9:00 AM – 11:00 AM',
      availability: 'busy',
      category: 'hods',
      avatar: 'PH',
      room: 'NCS Building, Room 210',
      bio: 'Academic head of the Physics department.',
      appointmentDuration: 15,
      slots: ['09:00', '10:00']
    },
    {
      id: 'hod-chemistry',
      name: 'Dr. [Name]',
      title: 'Head of Department',
      office: 'Department of Chemistry',
      faculty: 'Faculty of Natural & Computational Sciences',
      department: 'Chemistry',
      email: 'hod.chemistry@hu.edu.pk',
      phone: '+92-997-414164',
      officeHours: 'Monday – Friday, 9:00 AM – 11:00 AM',
      availability: 'available',
      category: 'hods',
      avatar: 'CH',
      room: 'NCS Building, Room 215',
      bio: 'Academic head of the Chemistry department.',
      appointmentDuration: 15,
      slots: ['09:00', '10:00', '11:00']
    },
    {
      id: 'hod-botany',
      name: 'Dr. [Name]',
      title: 'Head of Department',
      office: 'Department of Botany',
      faculty: 'Faculty of Biological & Health Sciences',
      department: 'Botany',
      email: 'hod.botany@hu.edu.pk',
      phone: '+92-997-414170',
      officeHours: 'Monday – Friday, 9:00 AM – 11:00 AM',
      availability: 'available',
      category: 'hods',
      avatar: 'BT',
      room: 'BHS Building, Room 101',
      bio: 'Academic head of the Botany department.',
      appointmentDuration: 15,
      slots: ['09:00', '10:00', '11:00']
    },
    {
      id: 'hod-zoology',
      name: 'Dr. [Name]',
      title: 'Head of Department',
      office: 'Department of Zoology',
      faculty: 'Faculty of Biological & Health Sciences',
      department: 'Zoology',
      email: 'hod.zoology@hu.edu.pk',
      phone: '+92-997-414171',
      officeHours: 'Monday – Friday, 9:00 AM – 11:00 AM',
      availability: 'available',
      category: 'hods',
      avatar: 'ZO',
      room: 'BHS Building, Room 110',
      bio: 'Academic head of the Zoology department.',
      appointmentDuration: 15,
      slots: ['09:00', '10:00', '11:00']
    },
    {
      id: 'hod-pharmd',
      name: 'Dr. [Name]',
      title: 'Head of Department',
      office: 'Department of Pharmacy',
      faculty: 'Faculty of Biological & Health Sciences',
      department: 'Pharmacy',
      email: 'hod.pharmacy@hu.edu.pk',
      phone: '+92-997-414172',
      officeHours: 'Monday – Thursday, 9:00 AM – 11:00 AM',
      availability: 'available',
      category: 'hods',
      avatar: 'PD',
      room: 'BHS Building, Room 201',
      bio: 'Academic head of the Pharmacy department.',
      appointmentDuration: 15,
      slots: ['09:00', '10:00', '11:00']
    },
    {
      id: 'hod-english',
      name: 'Dr. [Name]',
      title: 'Head of Department',
      office: 'Department of English',
      faculty: 'Faculty of Arts & Humanities',
      department: 'English',
      email: 'hod.english@hu.edu.pk',
      phone: '+92-997-414180',
      officeHours: 'Monday – Friday, 9:00 AM – 11:00 AM',
      availability: 'available',
      category: 'hods',
      avatar: 'EN',
      room: 'Arts Building, Room 105',
      bio: 'Academic head of the English department.',
      appointmentDuration: 15,
      slots: ['09:00', '10:00', '11:00']
    },
    {
      id: 'hod-economics',
      name: 'Dr. [Name]',
      title: 'Head of Department',
      office: 'Department of Economics',
      faculty: 'Faculty of Law & Social Sciences',
      department: 'Economics',
      email: 'hod.economics@hu.edu.pk',
      phone: '+92-997-414190',
      officeHours: 'Monday – Friday, 9:00 AM – 11:00 AM',
      availability: 'available',
      category: 'hods',
      avatar: 'EC',
      room: 'LSS Building, Room 201',
      bio: 'Academic head of the Economics department.',
      appointmentDuration: 15,
      slots: ['09:00', '10:00', '11:00']
    },
    // ── OFFICES ──────────────────────────────────────────────
    {
      id: 'admissions-office',
      name: 'Admissions Team',
      title: 'Admission Office',
      office: 'Admission Office',
      faculty: 'University Administration',
      department: 'Admissions',
      email: 'admissions@hu.edu.pk',
      phone: '+92-997-414120',
      officeHours: 'Monday – Saturday, 8:00 AM – 3:00 PM',
      availability: 'available',
      category: 'offices',
      avatar: 'AO',
      room: 'Admin Block, Ground Floor',
      bio: 'Handles all student admission queries, form submission, and enrollment.',
      appointmentDuration: 15,
      slots: ['08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '12:00', '13:00', '14:00']
    },
    {
      id: 'exam-office',
      name: 'Examination Team',
      title: 'Examination Office',
      office: 'Examination Office',
      faculty: 'University Administration',
      department: 'Examinations',
      email: 'exams@hu.edu.pk',
      phone: '+92-997-414121',
      officeHours: 'Monday – Friday, 9:00 AM – 2:00 PM',
      availability: 'available',
      category: 'offices',
      avatar: 'EO',
      room: 'Exam Block, Ground Floor',
      bio: 'Handles date sheets, roll numbers, result queries, and exam issues.',
      appointmentDuration: 15,
      slots: ['09:00', '09:30', '10:00', '10:30', '11:00', '12:00', '13:00']
    },
    {
      id: 'student-affairs',
      name: 'Student Affairs Team',
      title: 'Student Affairs Office',
      office: 'Student Affairs Office',
      faculty: 'University Administration',
      department: 'Student Affairs',
      email: 'studentaffairs@hu.edu.pk',
      phone: '+92-997-414122',
      officeHours: 'Monday – Friday, 9:00 AM – 3:00 PM',
      availability: 'available',
      category: 'offices',
      avatar: 'SA',
      room: 'Student Center',
      bio: 'Manages student welfare, societies, sports, events, and complaints.',
      appointmentDuration: 15,
      slots: ['09:00', '10:00', '11:00', '12:00', '13:00', '14:00']
    }
  ],

  // ──────────────────────────────────────────────────────────
  //  FACULTIES & PROGRAMS
  // ──────────────────────────────────────────────────────────
  faculties: [
    {
      id: 'ncs',
      name: 'Faculty of Natural & Computational Sciences',
      shortName: 'Natural & Computational Sciences',
      icon: '⚛️',
      color: '#4CAF50',
      gradient: 'linear-gradient(135deg, #1B4D3E 0%, #2E7D32 100%)',
      description: 'Advancing science, mathematics, and computing to solve real-world problems through research and innovation.',
      programs: [
        { name: 'BS Artificial Intelligence', type: 'BS', duration: '4 Years' },
        { name: 'BS Computer Science', type: 'BS', duration: '4 Years' },
        { name: 'BS Information Technology', type: 'BS', duration: '4 Years' },
        { name: 'BS Software Engineering', type: 'BS', duration: '4 Years' },
        { name: 'BS Data Science', type: 'BS', duration: '4 Years' },
        { name: 'BS Cyber Security', type: 'BS', duration: '4 Years' },
        { name: 'BS Bioinformatics', type: 'BS', duration: '4 Years' },
        { name: 'BS Mathematics', type: 'BS', duration: '4 Years' },
        { name: 'BS Statistics', type: 'BS', duration: '4 Years' },
        { name: 'BS Physics', type: 'BS', duration: '4 Years' },
        { name: 'BS Chemistry', type: 'BS', duration: '4 Years' },
        { name: 'BS Telecommunication', type: 'BS', duration: '4 Years' },
        { name: 'BS Environmental Sciences', type: 'BS', duration: '4 Years' }
      ]
    },
    {
      id: 'bhs',
      name: 'Faculty of Biological & Health Sciences',
      shortName: 'Biological & Health Sciences',
      icon: '🧬',
      color: '#00BCD4',
      gradient: 'linear-gradient(135deg, #006064 0%, #00838F 100%)',
      description: 'Cultivating scientific understanding of life and health to produce skilled professionals in biological and medical fields.',
      programs: [
        { name: 'BS Agriculture', type: 'BS', duration: '4 Years' },
        { name: 'BS Biotechnology & Genetic Engineering', type: 'BS', duration: '4 Years' },
        { name: 'BS Biochemistry', type: 'BS', duration: '4 Years' },
        { name: 'BS Botany', type: 'BS', duration: '4 Years' },
        { name: 'BS Microbiology', type: 'BS', duration: '4 Years' },
        { name: 'BS Zoology', type: 'BS', duration: '4 Years' },
        { name: 'Doctor of Pharmacy (Pharm-D)', type: 'Pharm-D', duration: '5 Years' }
      ]
    },
    {
      id: 'lss',
      name: 'Faculty of Law & Social Sciences',
      shortName: 'Law & Social Sciences',
      icon: '⚖️',
      color: '#FF9800',
      gradient: 'linear-gradient(135deg, #E65100 0%, #F57C00 100%)',
      description: 'Developing critical thinkers, legal professionals, and socioeconomic leaders to drive positive societal change.',
      programs: [
        { name: 'BBA', type: 'BBA', duration: '4 Years' },
        { name: 'BS Accounting & Finance', type: 'BS', duration: '4 Years' },
        { name: 'BS Business Analytics', type: 'BS', duration: '4 Years' },
        { name: 'BS Economics', type: 'BS', duration: '4 Years' },
        { name: 'BS Psychology', type: 'BS', duration: '4 Years' },
        { name: 'BS Sociology', type: 'BS', duration: '4 Years' },
        { name: 'BS Political Science', type: 'BS', duration: '4 Years' },
        { name: 'BS International Relations', type: 'BS', duration: '4 Years' },
        { name: 'Bachelor of Public Administration', type: 'BPA', duration: '4 Years' },
        { name: 'LLB', type: 'LLB', duration: '5 Years' },
        { name: 'BS Islamic & Religious Studies', type: 'BS', duration: '4 Years' }
      ]
    },
    {
      id: 'ah',
      name: 'Faculty of Arts & Humanities',
      shortName: 'Arts & Humanities',
      icon: '🎨',
      color: '#9C27B0',
      gradient: 'linear-gradient(135deg, #4A148C 0%, #6A1B9A 100%)',
      description: 'Nurturing creativity, cultural understanding, and communication skills through a rich blend of arts and humanities disciplines.',
      programs: [
        { name: 'BS English', type: 'BS', duration: '4 Years' },
        { name: 'BS Urdu', type: 'BS', duration: '4 Years' },
        { name: 'BS Education', type: 'BS', duration: '4 Years' },
        { name: 'BS Pakistan Studies', type: 'BS', duration: '4 Years' },
        { name: 'BS Archaeology', type: 'BS', duration: '4 Years' },
        { name: 'BS Architecture', type: 'BS', duration: '4 Years' },
        { name: 'BS Art & Design', type: 'BS', duration: '4 Years' },
        { name: 'BS Communication & Media Studies', type: 'BS', duration: '4 Years' },
        { name: 'BS Tourism & Hospitality', type: 'BS', duration: '4 Years' },
        { name: 'BS Conservation Studies', type: 'BS', duration: '4 Years' }
      ]
    }
  ],

  // ──────────────────────────────────────────────────────────
  //  STATS
  // ──────────────────────────────────────────────────────────
  stats: [
    { label: 'Programs Offered', value: 41, suffix: '+', icon: '📚' },
    { label: 'University Officials', value: 20, suffix: '+', icon: '🎓' },
    { label: 'Students Enrolled', value: 12000, suffix: '+', icon: '👨‍🎓' },
    { label: 'Faculties', value: 4, suffix: '', icon: '🏛️' }
  ],

  // ──────────────────────────────────────────────────────────
  //  CATEGORY LABELS
  // ──────────────────────────────────────────────────────────
  categories: {
    administration: { label: 'Top Management', icon: '🏛️' },
    directors: { label: 'Directors', icon: '📋' },
    deans: { label: 'Deans', icon: '🎓' },
    hods: { label: 'HODs / Chairmen', icon: '👨‍🏫' },
    offices: { label: 'University Offices', icon: '🏢' }
  }
};

// Export for use in other scripts
if (typeof module !== 'undefined') module.exports = HU_DATA;
